name: padding_scrollbar
description: A scrollbar widget that supports padding.
version: 0.0.4
author: Robert Mainzer <kontakt@rmainzer.de>
homepage: https://github.com/xonaman/flutter-padding-scrollbar/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter